### PR TITLE
Emit a 'release' event when a connection is released back to the pool

### PR DESCRIPTION
**Pull request by nihonjinrxs**
This PR has the `Pool` object emit a `'release'` event upon the release of a client/connection back to the pool.

We're experiencing an issue that feels quite similar to what's described in brianc/node-postgres#2262, and in reading through the comments there, I was interested to see @brianc's suggestion of [adding a `'release'` event as the corresponding bookend to the `'connect'` and `'acquire'` events](https://github.com/brianc/node-postgres/issues/2262#issuecomment-656751203). However, in searching the code, it seems this was never implemented, so I've implemented that here.

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
@brianc let me know if you need anything more from me on this. Happy to help get this merged in whatever way you need. Thanks!

**Comment by weyert** [comment]
Nice, looks like this could also be used to count the number of open connections?

**Comment by nihonjinrxs** [comment]
> Nice, looks like this could also be used to count the number of open connections?

You could, but I think it's probably easier to use [the existing properties](https://node-postgres.com/api/pool) `totalCount` and `idleCount` to understand connection count in the pool. There's also a `waitingCount` which counts requests waiting for a connection to be available.

**Comment by brianc** [comment]
This looks perfectly good to me! Thank you so much! Agree the symmetry here is nice and kinda long standing silly oversight on my part to not do that to begin with.  😄 ❤️

**Comment by nihonjinrxs** [comment]
Hey @brianc -- sorry for the delay in getting back to this. I've synced my fork, and CI seems to be running. Thanks!

**Comment by nihonjinrxs** [comment]
@brianc Any chance we can get this one merged soon?

**Comment by nihonjinrxs** [comment]
Hey, @brianc -- sorry to ping again, but it's been a while. Hoping to get this PR merged soon. We're currently operating off of a local branch incorporating this change, and I'd really like to be able to come back to the origin distribution if possible. Let me know if you need anything from me to make this happen. Thanks!

**Comment by nihonjinrxs** [comment]
@brianc just checking in again -- would love to get this PR merged soon, so we can get off this branch build. Let me know if there's anything more you need here.

**Comment by brianc** [comment]
sorry for delay! Will release it today!

**Pull request merged**
