### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vitaly-t**
Added reference to vitaly-t/pg-promise in chapter Extras.

### CODE REVIEW

**Comment by brianc** [comment]
Thanks @vitaly-t - your module looks cool!  Quick ? - can you move your link to the bottom? Generally we add them in order of the module author adding them to the README, thanks.

**Comment by vitaly-t** [comment]
@brianc ,

done, moved it to the bottom of the list ;)

**Comment by brianc** [comment]
Thanks @vitaly-t ! :dancer: Merging now. :heart:

**Comment by vitaly-t** [comment]
Cheers! :thumbsup:

**Pull request merged**
