### PR TITLE
Cursor: avoid closing connection twice if error received after destroy()

### PR DESCRIPTION
**Pull request by alxndrsn**
Fix for #1674, alternative to https://github.com/brianc/node-postgres/pull/2832.

### CODE REVIEW

**Comment by brianc** [comment]
Sorry for the delay here (things have been crazy over here recently).  This looks good to me. If @charmander doesn't have any thoughts on the contrary I'm happy to merge & release this.  Really appreciate your help & the test coverage!

**Comment by alxndrsn** [comment]
Thanks @brianc - all feedback very appreciated :slightly_smiling_face:

**Comment by alxndrsn** [comment]
@brianc @charmander is there anything I can do to improve this PR?

**Comment by alxndrsn** [comment]
Thanks @rafaell-lycan!

**Comment by alxndrsn** [comment]
> I believe this PR would fix my problem.

@nathanjcochran I see you have a neat repro at https://github.com/brianc/node-postgres/issues/1674#issuecomment-1563287449; any chance you can test this patch against that?

**Comment by alxndrsn** [comment]
@nathanjcochran Great news.  Do you think your repro is significantly different from the test case in this PR?  If so, should we consider turning it into an additional test case?

**Comment by alxndrsn** [comment]
Thanks @nathanjcochran - I'll give it a quick go.  If the test is good, any objections to adding it to this PR?

**Comment by alxndrsn** [comment]
@nathanjcochran looks like the test is good: https://github.com/alxndrsn/node-postgres/actions?query=branch%3Adont-close-cursor-twice-new-test-test++

**Comment by alxndrsn** [comment]
I've rebased this branch onto the latest `master`.  Prior to that I confirmed that tests were still failing _without_ the fix in `packages/pg-cursor/index.js`.

**Comment by nathanjcochran** [comment]
>  If the test is good, any objections to adding it to this PR?

@alxndrsn Go for it! Thank you!!

**Comment by alxndrsn** [comment]
Thanks @nathanjcochran - added :+1:

**Comment by alxndrsn** [comment]
@brianc @charmander is there anything I can do to improve this PR?  Very happy to discuss, or close the PR if there is no interest in merging it.

**Comment by charmander** [comment]
I’d like to know why `handleError` is called after completion and haven’t looked into it yet.

(code style doesn’t match, by the way)

**Comment by alxndrsn** [comment]
@charmander I'm happy to update the code style if that will help.  Do you have any pointers on what would need to change?

**Comment by lognaturel** [comment]
@charmander @brianc We've been running this in a fork for a year now and would really like to come back to mainline! Could one of you push the style changes that you want to this branch, maybe?

**Comment by alxndrsn** [comment]
I've rebased this branch onto `master`, and fixed all lint violations.

Interestingly two of the three new test cases now pass without the fix in this PR.  From https://github.com/brianc/node-postgres/actions/runs/6586450194/job/17894838346?pr=2836:

```
  error recovery
    ✓ recovers from a streaming error in a transaction
    ✓ handles an error on a stream after a plain text non-stream error
    ✓ does not crash when closing a connection with a queued stream
    1) should work if used after timeout error
    ✓ should work if used after syntax error
    ✓ should work after cancelling query (112ms)
```

**Comment by alxndrsn** [comment]
I've merged the latest `master` into this branch.

I've also run the tests against latest `master` without the fix, and there are two failures:

```
  2 failing
  1) error recovery
       should work if used after timeout error:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual
- []
+ [
+   {
+     d: 4
+   }
+ ]
      + expected - actual
      -[]
      +[
      +  {
      +    "d": 4
      +  }
      +]
      
      at /home/runner/work/node-postgres/node-postgres/packages/pg-query-stream/test/error.ts:109:12
      at Generator.next (<anonymous>)
      at fulfilled (test/error.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  2) error recovery
       should work after cancelling query:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual
- []
+ [
+   {
+     a: 1
+   }
+ ]
      + expected - actual
      -[]
      +[
      +  {
      +    "a": 1
      +  }
      +]
      
      at /home/runner/work/node-postgres/node-postgres/packages/pg-query-stream/test/error.ts:168:12
      at Generator.next (<anonymous>)
      at fulfilled (test/error.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

In addition, there seems to be some kind of shutdown problem when the fix is not included.

See: https://github.com/alxndrsn/node-postgres/actions/runs/8277192701/job/22647097080

**Comment by brianc** [comment]
Thank you so much! Your help is amazing!

**Comment by alessbelli** [comment]
This fix looks amazing, thank you for getting that over the finish line! I don't know what the general policy is here for cutting new tags, but I wondered when this would be tagged and published to npm as a new version? there hasn't been a new version in a while so I'd like to know whether it's best for us to wait for 8.12 or to use this commit.
Thanks again!

**Comment by brianc** [comment]
New version going out tomorrow! Typically doesnt take me this long…last day
of my
Job was today so gotta focus on spinning that down. Sorry for the delay. 🤪

**Comment by brianc** [comment]
New patch version out now! Sorry again for the delay

**Pull request merged**
