### PR TITLE
Add current Node 17 to CI and update LTS list

### PR DESCRIPTION
**Pull request by charmander**

### CODE REVIEW

**Comment by charmander** [comment]
@brianc Looks like CI has stopped working. You might need to migrate to travis-ci.com from .org? Or I can finish up the GitHub Actions branch.

**Comment by brianc** [comment]
Travis CI continues to break and be really frustrating in general.  Yes!
Definitely lets move to github actions. I just moved my company over to
them. If you share that branch I am happy to help push it over the finish
line if you need help as well.

**Comment by brianc** [comment]
ah beautiful. I'll try working on this this weekend, and then get through
my PR backlog & get some versions shipped.  Past month has been insane -
moving, a destination wedding, international travel, and a bunch of crazy
stuff at work so been really behind here. Catching up now though!

**Comment by charmander** [comment]
And FWIW, here's my branch (minus any "debug" commits at the end): https://github.com/charmander/node-postgres/commits/github-actions-ci

It's even more broken now than when I left it, though :D

**Comment by brianc** [comment]
Closing this because travis killed our integration with them multiple times.  Long live github actions! 🎉

**Pull request closed without merging**
