### PR TITLE
don't mutate params when preparing statement

### LINKED ISSUE #750: client.query(sqlString, params[], function) alters the given params[]
When supplying a parameters array to client.query the given array is modified (in my case it originally was an array of numbers and got transformed to an array of strings). This is not correct behaviour, I see the problem in the source code (query.js, line 143):

```
self.values[i] = utils.prepareValue(self.values[i]);
```

If transformation is needed it should be done on a clone of the passed array so that it doesn't break any logic in case the original array is reused somewhere else after the query.

I think a quick fix would be to change (query.js, line 14) from:

```
this.values = config.values;
```

to

```
this.values = config.values.slice();
```

### PR DESCRIPTION
**Pull request by devTristan**
Fixes #750

### CODE REVIEW

**Comment by langpavel** [comment]
:+1:

**Comment by seamusabshere** [comment]
@devTristan can you fix the test on here?

**Comment by devTristan** [comment]
@seamusabshere I haven't the foggiest idea why it's failing on that one postgres+node version combination. It might be transient or something stranger. It's on my TODO list.

**Comment by brianc** [comment]
Ah it's failing due to some stupid race condition in an error checking test I haven't fixed yet.  I'll merge this & look at that test later.  Thanks a lot for putting this together!

**Pull request merged**
