### PR TITLE
lazy load crypto utils

### PR DESCRIPTION
**Pull request by hloughrey**
Fix [2980](https://github.com/brianc/node-postgres/issues/2980)

### CODE REVIEW

**Review by charmander — APPROVED** [review]

**Comment by brianc** [comment]
Thank you!

**Comment by brianc** [comment]
hmmm tests are failing in CI

**Comment by mschilde** [comment]
Wouldn't the fix be simply removing the return outside the function? Or wrap everything after the return into an else block? Currently pg v.8.11+ is broken for a number of users.

**Comment by charmander** [comment]
> Wouldn't the fix be simply removing the return outside the function?

no

> Or wrap everything after the return into an else block?

sure

> let's

pr?

**Review by charmander — CHANGES_REQUESTED** [review]
crypto/utils is also imported by lib/client.

**Pull request closed without merging**
