### PR TITLE
Test pg@10.x on travis

### PR DESCRIPTION
**Pull request by brianc**
This is gonna be a bit messy until I get `pg@10.x` running in travis & setup w/ a scram enabled user. Once I do that I'll clean this up, enable the scram integration tests, merge, and release new minor version supporting that auth method.

### CODE REVIEW

**Comment by brianc** [comment]
I'm gonna try w/ a different blank repo to keep any potential spam to a minimum here until I get travis figured out 😬

**Comment by joelmukuthu** [comment]
FYI @brianc, Postgres 10 works out of the box with xenial. Sample config that works: 
https://github.com/knorm/knorm/pull/235/files#diff-354f30a63fb0907d4ad57269548329e3R7

**Comment by brianc** [comment]
ohhhh awesome! Thank you! Will get this updated. :) I tried w/ a different
repo for several hours and grew frustrated.

**Comment by joelmukuthu** [comment]
You’re welcome :) I went through the same pain myself before finding a comment in a github issue pointing to xenial. Not sure why they haven’t updated the docs

**Pull request closed without merging**
