### PR TITLE
Add a license comment to a source code

### PR DESCRIPTION
**Pull request by kitakappa**
This PR makes the open source licensing clearer.
* Add license header comments to source code files.

### CODE REVIEW

**Comment by brianc** [comment]
Is there a reason for this? I'm not a fan of license headers in every source file.

**Comment by kitakappa** [comment]
The reason.. To use this in more people.
License header is necessary for by 1 file when I want to use OSS in a stubborn company :l
In addition, even if a file fall away from package, a license is clear.

I think license header is redundant, but think that it is good if users increase.

**Comment by brianc** [comment]
@kitakappa if this will make it easier for you to use this at your company I'll merge it in, just for you. ;)

**Comment by kitakappa** [comment]
@brianc Thank you for consideration. Yes, legal department in my company is very very stubborn. :X
I'm so happy if merge this. :)

**Comment by brianc** [comment]
Hey @kitakappa - I made some changes which caused a merge conflict here. :( Sorry about that - if you can resolve the merge conflict I'll get this merged into the code base ASAP!

**Comment by illiriks** [comment]
Hey; I resolved the merge conflict (one file was `rm`ed).

**Comment by brianc** [comment]
Closed with #1065

**Comment by kitakappa** [comment]
@brianc @illiriks Sorry to be late. Thank you for fix conflict and marge 👍
It was saved very much. :-)

**Pull request closed without merging**
