### PR TITLE
Fix newlines in string array

### LINKED ISSUE #1147: Newline in text array loses backslash
### Issue:

When inserting/updating a column of type `text[]`, newlines get converted to a character `n`.
### How to reproduce:

Run the following code:

```
var pg = require('pg');
var client = new pg.Client();
client.connect(function (err) {
  client.query('CREATE TABLE test (array_test text[])', function(err, result) {
    client.query('INSERT INTO test (array_test) VALUES ($1)', [['hello\nworld']], function (err, result) {
      client.query('SELECT * FROM test', function (err, result) {
        console.log(result.rows[0]);
        client.end();
      })
    })
  })
});
```
#### Behaviour:

The console.log is missing a backslash:

```
{ array_test: [ 'hellonworld' ] }
```
#### Expected behaviour

The console.log should output a string including the backslash:

```
{ array_test: [ 'hello\nworld' ] }
```
### Quick fix

Quick fix for this issue is to change `/lib/utils.js:28` to:

```
result = result + JSON.stringify(prepareValue(val[i])).replace('\\n', '\n');
```
### Other notes:

Not related to #895 (which seems to be fixed atm)

### PR DESCRIPTION
**Pull request by jehna**
Fixes #1147

### CODE REVIEW

**Comment by jehna** [comment]
Checks are failing for the error:

```
Message: role "sfalsdkf" does not exist
```

...but I'm getting that in the master also. Is this a broader problem?

**Comment by swarthy** [comment]
Same here #1152

**Comment by charmander** [comment]
Added a pull request for some other things that shouldn’t be escaped.

Also, failures are fixed by brianc/node-pg-pool#31.

**Comment by brianc** [comment]
I merged https://github.com/brianc/node-postgres/pull/1177 to fix this! Will be pushing a patch version to npm shortly.

**Pull request closed without merging**
