### PR TITLE
Fix JSON-escaped characters in string array

### PR DESCRIPTION
**Pull request by charmander**
Improved fix for #1147 over #1148.

### CODE REVIEW

**Comment by brianc** [comment]
@charmander - you're amazing.  Would you like collaborator access to the repo so in any case where I'm out I don't end up blocking you?  I'd love to have more co-maintainers helping out!

**Comment by brianc** [comment]
Since CI is borked (you fixed it!! but on another PR) I'll run the tests locally & if they pass I'll get this one merged in.

**Comment by brianc** [comment]
Works! Merged! Thank you! ❤️

**Comment by charmander** [comment]
@brianc Sure, thanks! And thank you for going through all this again.

**Pull request merged**
