### PR TITLE
Include pg-connection-string into monorepo

### PR DESCRIPTION
**Pull request by brianc**
After [some](https://github.com/brianc/node-postgres/pull/2105) [discussions](https://github.com/iceddev/pg-connection-string/issues/37) I'm going to bring pg-connection-string into this repo.  This will help out w/ making it easier to control the SSL parameters from the connection string.

### CODE REVIEW

**Comment by brianc** [comment]
note: need to merge this with a _merge_ commit to preserve history.

**Comment by brianc** [comment]
@hjr3 Thanks for your help in getting this moved over!  

Before I can take dependency on this version from within the monorepo I'd like to make sure I have enough access to the npm package on npmjs.com to be a maintainer of it long term.  That means enough access to publish to the package & add/remove collaborators.  You're absolutely welcome to be a co-owner...I just need to have enough access in case you ever decide you don't wanna bother anymore so we can have continuity of ownership!  If there's anything you need from me to help w/ this that isn't able to be discussed in public please feel free to email me or just ping me here!

**Comment by hjr3** [comment]
Glad I could help. I pinged the repo (and I think npm?) owners in https://github.com/iceddev/pg-connection-string/issues/37#issuecomment-620720757 . I believe @monteslu is the person who can help with the transition.

**Comment by monteslu** [comment]
Not super familiar with monorepos yet.  We get to keep the commit history with moving this right?

**Comment by brianc** [comment]
> Not super familiar with monorepos yet. We get to keep the commit history with moving this right?

Indeed - as long as I merge this w/ a merge commit (which is the merge method I have selected RN) 
image

Then it should be good. I used this command to pull in the full history of the other repo:

```
~/src/node-postgres (bmc/pg-connection-string)
$ git subtree add --prefix packages/pg-connection-string https://github.com/iceddev/pg-connection-string.git master
```

which is what I did when I merged in pg-pool, pg-cursor, etc into this repo.  You can see the huuuuge list of commits above, they should all be preserved! 👯

**Comment by monteslu** [comment]
perfect!

I've added you to the npm repo.

**Comment by brianc** [comment]
awesome thanks @monteslu - I'm gonna try publishing a new patch version now.  You might wanna redirect the existing iceddev repo over here.  Please feel free to collab & contribute here as much or as little as you want.  I'll consider myself a "co-owner" in that I'll take responsibility for anything that merges in and shepherd the project if you get burnt out or want to go do something else, but I don't plan on standing in your way at all if you want to continue to drive it forward yourself over here too! ❤️  

The main motivation here is to make it easier to integrate changes to `pg-connection-string` back into the mainline as the two repos are kinda tightly coupled.

**Comment by brianc** [comment]
```
lerna http fetch PUT 200 https://registry.npmjs.org/pg-connection-string 2945ms
Successfully published:
 - pg-connection-string@2.2.1
lerna success published 1 package
   Done in 35.10s.
```
💃 

I'll work on getting a semver minor release of pg & friends out tomorrow to re-baseline on top of this version of `pg-connection-string`.  Work is pretty crazy right now so might not be until end of week but _probably_ tomorrow! 🤞

**Pull request merged**
