### PR TITLE
Support options connection parameter

### LINKED ISSUE #2214: Support options/PGOPTIONS connection parameter/environment variable
Postgres describes this parameter here: https://www.postgresql.org/docs/9.1/libpq-connect.html#LIBPQ-CONNECT-OPTIONS. This driver should support passing through the parameter, or reading it from an environment variable.

This was previously requested in this issue: https://github.com/brianc/node-postgres/issues/1482 I believe that issue was closed mistakenly. Here is [the Postgres source code](https://github.com/postgres/postgres/blob/7dd777938bbeae8113f73849920a5b19bef723d9/src/interfaces/libpq/fe-connect.c#L253) that looks at this parameter.

It looks like the fix would be in the `ConnectionParameters` object. I am happy to create a PR to addrss this issue.
https://github.com/brianc/node-postgres/blob/70cf4dc6edbe1e4d5b6e4ddbe9ebaabc656ff738/packages/pg/lib/connection-parameters.js#L121-L126

### PR DESCRIPTION
**Pull request by rafiss**
This supports the connection parameter documented here:
https://www.postgresql.org/docs/9.1/libpq-connect.html#LIBPQ-CONNECT-OPTIONS

fixes #2214

### CODE REVIEW

**Comment by brianc** [comment]
wow that was fast! Do you know of a param I could send to the backend & then query the backend to verify it's taken effect?  I'd like to add a test that does something like...

```js
const client = new Client({ options: '--foo=bar' })
await client.connect()
const { rows } = await client.query('SELECT session_options')
assert(rows[0].key === 'foo')
assert(rows[0].value === 'bar')
```

or something like that.  The specifics aren't really ironed out there I just always like to test "round tripping" the data when I can.  I'll write this test if you know of how it could work?

**Comment by sehrope** [comment]
@brianc How about `default_transaction_isolation`? I have a feeling that one won't be going away:

```
$ psql \
    -c 'SHOW default_transaction_isolation'
 default_transaction_isolation 
-------------------------------
 read committed
(1 row)

$ PGOPTIONS='--default_transaction_isolation=serializable' psql \
    -c 'SHOW default_transaction_isolation'
 default_transaction_isolation 
-------------------------------
 serializable
(1 row)
```

**Comment by boromisp** [comment]
With recent postgres versions you can use custom namespaced variables:

```bash
PGOPTIONS="-c example.foo=bar" psql -c "SHOW example.foo"
 example.foo
-------------
 bar
(1 row)

psql -c "SHOW example.foo"
ERROR:  unrecognized configuration parameter "example.foo"
```

**Comment by rafiss** [comment]
Doing a round-trip test definitely sounds good to me. And thanks for taking on the task of writing it!

I'd agree with using a custom namespaced variable like how @boromisp posted. I think the `-c name=value` syntax is needed to set it.

**Comment by boromisp** [comment]
I think you will have to parse these parameters and [include them in the startup message](https://github.com/brianc/node-postgres/blob/bf469399b88bcdf86eff096fd0dd05684adc1117/packages/pg/lib/client.js#L373) for the JavaScript client.

**Comment by rafiss** [comment]
> I think you will have to parse these parameters and [include them in the startup message](https://github.com/brianc/node-postgres/blob/bf469399b88bcdf86eff096fd0dd05684adc1117/packages/pg/lib/client.js#L373) for the JavaScript client.

Ah thanks, I'd missed that earlier. Just updated.

**Comment by boromisp** [comment]
The https://github.com/brianc/node-postgres/issues/2103 issue could be fixed by setting the `statement_timeout` for the native driver in the `options` parameter:

```js
var escapeOptionValue = function (value) {
  return ('' + value).replace(/\\/g, '\\\\').replace(/ /g, '\\ ')
}

var addOption = function (options, config, optionName) {
  var value = config[optionName]
  if (value !== undefined && value !== null) {
    options.push('-c ' + optionName + '=' + escapeOptionValue(value))
  }
}

ConnectionParameters.prototype.getLibpqConnectionString = function (cb) {
  // ...
  var options = []
  if (this.options) {
    options.push(this.options)
  }
  addOption(options, this, 'statement_timeout')
  if (options.length > 0) {
    params.push('options=' + quoteParamValue(options.join(' ')))
  }
  // ...
}
```

An other (undocumented) config parameter that doesn't work with the native driver is `idle_in_transaction_session_timeout`. This could also be fixed the same way.

(The `unsupported startup parameter: statement_timeout` error in #2103 is probably related to this: https://www.pgbouncer.org/config.html#ignore_startup_parameters)

**Comment by brianc** [comment]
Hey sorry for the delay! I was out on vacation & just getting back...I'll take a look at this tomorrow! ❤️

**Comment by brianc** [comment]
@rafiss I have included a patch file for an integration test

https://cloudup.com/cHnXN0tuoD6

If you apply that patch to your branch I can merge this & release a new minor version w/ the support added.  Thanks for your work here & sorry for the delay!

**Comment by brianc** [comment]
or actually i can just merge this & then add the test myself. :)

**Comment by brianc** [comment]
Thanks for the PR! I'll release this tomorrow morning so I can make sure it doesn't cause weird regressions in anyone's systems.  (it shouldn't...but you never know)

**Comment by rafiss** [comment]
Thank you @brianc! Let me know if anything comes up.

**Comment by brianc** [comment]
Released as `pg@8.3.0`

**Pull request merged**
