### PR TITLE
Fix for server enconding when using SQL_ASCII and latin1 enconding

### PR DESCRIPTION
**Pull request by ederavilaprado**
Encodes the string as the same as the `client_encoding` when provided.

This is a way to fix problems when ussing characters outsite the regular ASCII table, like the char `°`, who is the number 176 decimal at the ISO-8859-1 ASCII table (https://en.wikipedia.org/wiki/Degree_symbol#Encoding).

Example using the same char:

```javascript
> new Buffer([176])
<Buffer b0>
> new Buffer([176]).toString('utf8')
'�'
> new Buffer([176]).toString('latin1')
'°'
```

### CODE REVIEW

**Comment by JCornat** [comment]
It is superfluous, but shouldn't `client_encoding` parameter be in CamelCase, like `clientEncoding`, for consistency with the whole project ?

**Comment by ederavilaprado** [comment]
I actually kept this name `client_encoding` because this already exists in the config object (is used when creating the connection string).

I found this when reading this comment: https://github.com/brianc/node-postgres/issues/906#issuecomment-260345891

It seems easier to reintegrate without generating side effects.

**Comment by brianc** [comment]
Thanks for putting this together @ederavilaprado! Really appreciated.

@JCornat I see what you're saying about camelCase.  That's something we might be able to change in a semver major change, since it'd subtly break in a patch release, but I'm open to it.  What do you think?

**Comment by JCornat** [comment]
Indeed (https://github.com/ederavilaprado/node-postgres/blob/297f90cc8143297aa2937f61ac88b10b33fb3c21/lib/connection-parameters.js#L59), sorry for my comment !

**Comment by brianc** [comment]
Hey @ederavilaprado - would you have a self-contained script or something I could use to make a test for this feature?  I don't want to accidentally break this in the future because there's no test for it.  I can add the test myself I just want to see a script demonstrating a different encoding & checking to make sure it deserializes correctly.

**Comment by JCornat** [comment]
@brianc Maybe it is not a bad thing to keep it how it currently is, my comment is just unnecessary

**Comment by brianc** [comment]
Published new version at `pg@6.4.0`! 

@JCornat okay cool. 😄 thanks for your help!

**Comment by ederavilaprado** [comment]
Hey @brianc, i will create something ASAP to help you with the tests... i'm not sure if i can do this before friday unfortunatelly.

I'll let you know as soon as I have something ready.

**Pull request merged**
