### PR TITLE
Move Extras section from README.md to Github wiki

### PR DESCRIPTION
**Pull request by langpavel**

### CODE REVIEW

**Comment by brianc** [comment]
I love this! Thank you!

**Comment by vitaly-t** [comment]
@brianc + @langpavel 

This dropped hammer on the visiting statistics for those links, I can see it from the stat.

Most people will not be visiting this separate page, because it is no longer obvious.

Not good for promoting extensions for this library.

**Comment by langpavel** [comment]
Hey, I created this PR because there are more concurrent packages that solve same problem.

**Comment by vitaly-t** [comment]
@langpavel what concurrent packages? what problem? I don't follow.

**Comment by langpavel** [comment]
@vitaly-t if anybody visit this PR; There is place until somebody else close this :-)

**Pull request merged**
