### PR TITLE
Update transactions.mdx

### PR DESCRIPTION
**Pull request by abel1534**
Hi Brian,
I was implementing transactions and the documentation says we shouldn't use pool.query but the sample code provided looks like it is using "const pool = new Pool()". Shouldn't it be using new Client() instead of new Pool() ? What am I missing?

Thank You so much!

### CODE REVIEW

**Comment by charmander** [comment]
`pool.query` can’t use a transaction, but running a transaction on a client obtained by `pool.connect` is fine.

**Comment by abel1534** [comment]
@brianc Thank You so much for your response. That makes sense. 
When I do try the example in the documentation, in the finally block,  where I have my pgClient.release() method, I get error saying "Property 'release' does not exist on type 'Pool'.

Sample code
try {
    await pgClient.query('BEGIN')
     ......
     await pgClient.query('BEGIN')
} catch(e) {
   await pgClient.query('ROLLBACK')
   throw e
} finally {
   pgClient.release()
}

**Comment by charmander** [comment]
`pgClient` should be a client obtained from the pool with `pool.connect`, not the pool itself.

**Comment by AbelAbrah** [comment]
@charmander Thank you so much. I have implemented it according to your recommendation and it is working. I appreciate it.

**Pull request closed without merging**
