### PR TITLE
Use bytea parameter type for Buffers

### LINKED ISSUE #1849: Error with null character in parameter
```js
client.query('SELECT $1::bytea as buffer', [new Buffer(1)])
```

results in

```
ERROR: invalid byte sequence for encoding "UTF8": 0x00
```

### PR DESCRIPTION
**Pull request by pauldraper**
Fixes #1849

### CODE REVIEW

**Comment by brianc** [comment]
Thanks @pauldraper - would you mind fixing the lint so the tests can run & pass? Really appreciate the work here!

**Comment by brianc** [comment]
I'll need to double-check w/ the current behavior of using buffers as parameters.  This _might_ be backwards incompatible if it changes existing behavior.

**Comment by sehrope** [comment]
@pauldraper Are you seeing this error with the native driver (i.e. "pg-native"), the pure JS one, or both?

I'm not able to reproduce this with the pure-JS driver and I think it's specific to pg-native. The native driver transforms all query parameters to strings and that's where the zero-byte issue comes in (PostgreSQL strings can't have zero bytes). See here for more details on pg-native parameter handling: https://github.com/brianc/node-postgres/issues/1680#issuecomment-401631727

Rather than deal with this one case here, the real fix may be changes to pg-native to handle parameter transformation for Buffer (ex: to hex) and possibly other types as well.

**Comment by charmander** [comment]
#1849:

> I was not using native. It appears that I actually had the problem with the string `'\0'`, not `new Buffer(1)`.

**Pull request closed without merging**
