### PR TITLE
Replace semver with optional peer dependencies

### PR DESCRIPTION
**Pull request by TrySound**
See example https://github.com/sindresorhus/gulp-chown/blob/bb74168c957b3a94f122aafcecf7ebc87088ec46/package.json#L42-L49

This feature is supported by both npm and yarn.

### CODE REVIEW

**Comment by TrySound** [comment]
cc @brianc

**Review by charmander — APPROVED** [review]
Seems super under-documented in npm, but usable now: https://github.com/npm/rfcs/issues/221#issuecomment-695127530

Thanks!

**Comment by TrySound** [comment]
Yes, this feature was first added in yarn and not that long ago in other package managers.

**Comment by brianc** [comment]
Wow this is awesome, thank you.

**Pull request merged**
