### PR TITLE
Parse date type as local time

### PR DESCRIPTION
**Pull request by benighted**
Resolves issue #510, but is a breaking change.  Handle with care :smile: 
Updated failing test case as well.

### CODE REVIEW

**Comment by alejandrolsca** [comment]
@brianc is there a way to set the timezone in node-postgres? I tried to find it in the documentation without success, i found an environment variable PGTZ here https://www.postgresql.org/docs/current/static/libpq-envars.html but i had not success trying to guess the configuration in the pool connection i.e.
`const pool = new Pool({
        connectionString: '......',
         timezone: 'America/Chihuahua'
    })`
also tried to set the timezone with a query as follows
`await client.query("SET timezone = 'America/Chihuahua';")`
but didn't worked
in fact what im trying to do is to set the timezone dynamically, so the query will be at the end as follows
`await client.query("SET timezone = $1;")`

can you give me start point to solve this issue, maybe im not looking in the right place. Thanks in advance for your support

**Comment by jrf0110** [comment]
@alejandrolsca generally you'd use something like `at time zone $1` in your queries:

```sql
-- Display the timestamp in the timezone of the object
select
  orders.created_at at time zone orders.timezone
from orders
```

**Comment by alejandrolsca** [comment]
@jrf0110 I was aware of that way, so its not recommended to use SET timezone.....? at this moment looks like a good solution, but in the near future could i have some problems? scalability issues? just wonder, also still wondering why SET timezone.... didnt work, even if you call that query in node postgres its override by postgres.conf?

**Comment by jrf0110** [comment]
I believe `SET timezone` will simply set the timezone the database is in. Try something like:

```sql
set timezone = 'America/Chicago';
select now();
```

**Comment by alejandrolsca** [comment]
@jrf0110 well the problem here is that it doesn't work in node-postgres, at least not for me, if I execute those queries in DBMS it works, but not by doing it with node-postgres library as follows:
`client.query("SET timezone = 'America/Chihuahua';")
  client.query("My query with dates here")`

**Pull request merged**
