### PR TITLE
Convert Query to an ES6 class

### PR DESCRIPTION
**Pull request by charmander**
The last missing `new` deprecation warning for pg 8.

### CODE REVIEW

**Comment by sehrope** [comment]
LGTM.

Why just this one file though and not also Result and Connection?

**Comment by charmander** [comment]
@sehrope #2021 added the warning to constructors that worked without `new`. `Result` and `Connection` already break when used without `new`, so they can be upgraded at any time without backwards compatibility issues.

**Comment by sehrope** [comment]
Ah makes sense. Thanks for the explanation.

**Comment by brianc** [comment]
Ah nice - I'll review this one (it's a big bigger) toady & then merge it.  Outside of this - anything left u know of outstanding for 8.0? I really want to tackle this performance stuff for a few weeks.

**Comment by charmander** [comment]
> anything left u know of outstanding for 8.0?

Not that I can think of!

**Comment by brianc** [comment]
sorry for the delay - corona virus panic and economic downturn causing a lot of disruption and general anxiety for me.  Will be getting on this today & will try to get 8.0 out tomorrow! Stay healthy. ❤️

**Pull request merged**
