### PR TITLE
#701 Expose error fields added in PG 9.3.

### PR DESCRIPTION
**Pull request by rpedela**
Several error fields were added in PG 9.3:
* schema
* table
* column
* data type
* constraint

This PR exposes them in the returned Error object.

### CODE REVIEW

**Comment by brianc** [comment]
@rpedela thank you so much!  Quick question...is there any way you could write a test for this?  I know it's postgres version dependent...you could use [this function](https://github.com/brianc/node-postgres/blob/ac0d1c71c2a29fff42aac42d70e87d95ba1b595f/test/integration/test-helper.js#L17) to only run the test if the database version supports it.  Here's an [example](https://github.com/brianc/node-postgres/blob/ac0d1c71c2a29fff42aac42d70e87d95ba1b595f/test/integration/client/json-type-parsing-tests.js#L12)

**Comment by rpedela** [comment]
Tests added. I am not sure how to trigger the "data type" error field, but the others are tested. I am happy to add another test for the "data type" error field if someone knows how to trigger it.

**Comment by brianc** [comment]
@rpedela awesome! :clap: :dancer:  

Will push a new minor version with this change later today. :+1:

**Comment by rpedela** [comment]
Thanks! :)

**Pull request merged**
