### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by charmander** [comment]
If there’s a specific dependency that needs updating, the PR should just update that dependency. Need to be careful about backwards compatibility. (pg-types 1.13, for example, is not actually backwards-compatible with 1.12.)

**Comment by kibertoad** [comment]
@charmander What about dev dependencies? Should be safe enough to update these?..

**Comment by charmander** [comment]
Which dev dependency needs an update?

**Comment by kibertoad** [comment]
@charmander Yeah, pretty much ESLint. Shall I create a PR just for that?

**Pull request closed without merging**
