### PR TITLE
In order for the command line execution to finish

### PR DESCRIPTION
**Pull request by wallymathieu**
In the example, it looks like it's missing a client end.

### CODE REVIEW

**Comment by brianc** [comment]
Thanks! Sorry for the delay in getting to this - been buried recently.

**Comment by wallymathieu** [comment]
No problem!

**Comment by dogles** [comment]
Is this correct? It seems like this would destroy the connection, which is the whole point of the connection pooling example...

**Comment by wallymathieu** [comment]
Sounds like I browsed the code and didn't read the comment. As the code reads, it reads like a command line app. Perhaps an express site that answers with some info would be clearer?

**Pull request merged**
