### PR TITLE
Buffer without new is now deprecated in node.js

### PR DESCRIPTION
**Pull request by adi**

### CODE REVIEW

**Comment by desnet** [comment]
I also have this bug. What's with this pull request?

**Comment by adi** [comment]
This pull request solves the deprecation warning mentioned in the subject.

**Comment by desnet** [comment]
Yes, I understand what the problem is. I want this issue resolved.

**Comment by AlexTes** [comment]
Duplicate of #1156.

**Comment by brianc** [comment]
Closing as duplicate

**Pull request closed without merging**
