### PR TITLE
crypto for edge runtime

### PR DESCRIPTION
**Pull request by artemavrin**

### CODE REVIEW

**Comment by charmander** [comment]
`globalThis.crypto` is already there.

**Comment by artemavrin** [comment]
ok, I just want to fix this error in nextjs middleware

```
Error: The edge runtime does not support Node.js 'crypto' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at (node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/globals.js:29:18)
    at (node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/crypto/utils-webcrypto.js:21:31)
    at (webpack/bootstrap:21:0)
    at (node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/crypto/utils.js:8:2)
    at (webpack/bootstrap:21:0)
    at (node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/crypto/sasl.js:2:15)
    at (webpack/bootstrap:21:0)
    at (node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:5:11)
    at (webpack/bootstrap:21:0)
    at (node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/index.js:3:13)
```

how can we solve this problem?

**Comment by constantgillet** [comment]
I also have this error in NextJS middleware

**Comment by charmander** [comment]
> The problem is not that you are not using webcrypto.

Yes, and that’s not the problem with the pull request (which did the equivalent of `globalThis.crypto || globalThis.crypto`).

Your proposal looks more correct, so feel free to make a pull request.

**Comment by ETHANTALJAFFE** [comment]
Hey, still having issues with pg in my middleware.js when running nextjs locally. 

Even when using pg@8.12.0 it seems like it still imports nodejs crypto like this `const nodeCrypto = require('crypto')`.

Could it be that this change was not published to npm somehow?
*  I am using Bun for running locally and installing packages.
* I tried uninstalling pg, deleting bun.lockb file and reinstalling and I am still seeing the nodejs crypto import inside of the utils-webcrypto file

**Comment by ETHANTALJAFFE** [comment]
I created a fix locally but I don't seem to have permission to publish my branch to the repo in order to create a PR. 
Can anyone please let me know how I can move forward? 
Thanks :)

**Comment by artemavrin** [comment]
I figured out this issue. We should separate providers and other configuration like this

**auth.config.ts**
```ts
import type { NextAuthConfig } from 'next-auth';

export const authConfig = {
  pages: {
    signIn: '/login',
  },
  providers: [
    // added later in auth.ts since it requires bcrypt which is only compatible with Node.js
    // while this file is also used in non-Node.js environments
  ],
  callbacks: {
    authorized({ auth, request: { nextUrl } }) {
     // your code here ...
      return true;
    },
  },
} satisfies NextAuthConfig;
```

**auth.ts**
```ts
// imports block
export const { auth, signIn, signOut } = NextAuth({
  ...authConfig, // <- from auth.config.ts
  providers: [
    Credentials({
      async authorize(credentials) {
        // auth code here ...
      },
    }),
  ],
});
```

**middleware.ts**
```ts
import NextAuth from 'next-auth';
import { authConfig } from './auth.config';

export default NextAuth(authConfig).auth;

export const config = {
  // https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher
  matcher: ['/((?!api|_next/static|_next/image|.png).*)'],
};
```

So you can use pg or drizzle in auth.ts and import other configs in middleware from auth.config.ts

**Pull request closed without merging**
