### PR TITLE
Stream end

### PR DESCRIPTION
**Pull request by Elexy**

### CODE REVIEW

**Comment by Vratislav** [comment]
@Elexy hello, this is something that I was thinking of adding because our connections were not closing correctly when running against postgres on Azure. Why have you closed it?

**Comment by Elexy** [comment]
The tests aren't passing: https://travis-ci.org/brianc/node-postgres/jobs/362160404
It's a bit beyond me why.

**Comment by Vratislav** [comment]
@Elexy I will look into it.

**Comment by Vratislav** [comment]
@Elexy I've submitted new PR with passing tests and a proper write-up: #1608

If you are ok with it, you can close this PR in favor of the one mentioned above.

Thanks for pointing the fix into right direction. 👍

**Pull request closed without merging**
