### PR TITLE
Add PostgreSQL 10 to CI

### PR DESCRIPTION
**Pull request by charmander**
and change to Ubuntu 18.04 so building OpenSSL isn’t necessary, and move old PostgreSQL version tests to the latest Node LTS.

Depends on #1946.

### CODE REVIEW

**Comment by brianc** [comment]
Sorry for not seeing this - if you rebase on master does this build cleanly now? Would be happy to merge when it does!

**Comment by charmander** [comment]
@brianc Not quite, but I’ve fixed it. :)

**Comment by brianc** [comment]
amazing!! Thank you.  Do you have experience w/ postgres & self-signed certs? I'd love to write some tests against our whole client certificate checking snafu from earlier.

**Comment by charmander** [comment]
@brianc Yep, I can try that in a few days.

**Pull request merged**
