### PR TITLE
Added default value to prevent error queryCallback is not a function

### PR DESCRIPTION
**Pull request by drzippie**
fix issue #1860 

Set default value to prevent Fatal exception with timeouts in a queryStream

### CODE REVIEW

**Review by charmander — CHANGES_REQUESTED** [review]
Ignoring the event doesn’t seem like the right fix. At a glance, it looks like it should raise an error event? Or maybe not support query timeouts?

**Comment by drzippie** [comment]
the fix is a "fast" fix,  queryStream uses Cursor and query.callback always is undefined
```
 FATAL: uncaughtException
    error: {
      "type": "TypeError",
      "message": "queryCallback is not a function",
      "stack":
          TypeError: queryCallback is not a function     
```

The other fix need to rethink and change how to deal with a timeout. 

Specifying a default value for that variable as callable allows us to use it even if the timeout management is not correctly resolved.

**Comment by drzippie** [comment]
Added a test:

without the change the test fails:

```

2560-tests.js
  empty query.callback do not throw fatal exception ✔
Message: queryCallback is not a function
TypeError: queryCallback is not a function
    at Query.query.callback (/workspace/packages/pg/lib/client.js:549:9)
    at Query.handleError (/workspace/packages/pg/lib/query.js:128:19)
    at /workspace/packages/pg/lib/client.js:75:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
   ```
   
 The test only makes a query (with timeout) setting callback as "undefined"

**Comment by drzippie** [comment]
added same change to native client.js
without this change:
```
2560-tests.js (native)
  empty query.callback do not throw fatal exception ✔
Message: queryCallback is not a function
TypeError: queryCallback is not a function
    at Timeout.setTimeout [as _onTimeout] (/home/travis/build/brianc/node-postgres/packages/pg/lib/native/client.js:185:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by drzippie** [comment]
Removed new test from PR: Fail other test in lts/carbon (https://travis-ci.com/github/brianc/node-postgres/builds/228104653)

without this new test the build do not fail ¿?

--- test file:  packages/pg/test/integration/gh-issues/2560-tests.js --- 

```
'use strict'

const pg = require('../../../lib')
const helper = require('../test-helper')
if (helper.args.native) return // don't run in native

var Query = helper.pg.Query

const suite = new helper.Suite()

suite.test('empty query.callback do not throw fatal exception', async (done) => {
  const config = {
    query_timeout: 100,
  }
  const notExpectedErr = new Error('queryCallback is not a function')
  var errorReceived = undefined

  try {
    var client = new Client(config)
    await client.connect()
    var sleepQuery = 'select pg_sleep($1)'
    var queryConfig = {
      name: 'sleep query',
      text: sleepQuery,
      values: [2],
      callback: undefined,
    }
    await client.query(new Query(queryConfig))
    await client.end()
  } catch (error) {
    if (error === notExpectedErr) {
      done(new Error('Received error queryCallback is not a function'))
    }
  }
  done()
})
```

**Review by drzippie — COMMENTED** [review]
The code was changed

**Comment by idandagan1** [comment]
Hi,
When are you guys planning to merge this?

**Comment by charmander** [comment]
It needs working tests. If you can fix https://app.travis-ci.com/github/brianc/node-postgres/jobs/511426643, that’ll help.

**Comment by brianc** [comment]
> Hi,
> When are you guys planning to merge this?

There's some code in the original issue. I can use that to write a test & fix. I'll add this to my TODO list & hopefully get to it this week/weekend.  Then a quick lil' release & we should be good.

**Comment by avivshafir** [comment]
+1 for merging this ASAP, thanks!

**Comment by mmtdm** [comment]
+1 for merging this ASAP, thanks!

**Comment by yaverin** [comment]
Please provide ETA for this fix - to prevent Fatal exception using "query_timeout" with queryStream.

**Comment by karunmotorq** [comment]
@brianc Will this be merged? We're encountering an error using pg-promise which this would fix

**Comment by brianc** [comment]
> Will this be merged? We're encountering an error using pg-promise which this would fix

need tests to merge this. Generally I don't merge PRs w/o tests unless they're trivial changes or documentation changes.  If you wanna write a test & it passes I'll happily merge it!

**Comment by brianc** [comment]
no tests still - closing

**Pull request closed without merging**
