### PR TITLE
Fixes #1105

### LINKED ISSUE #1105: TypeError: Cannot read property 'name' of null
First off, thanks for the library! Overall it's been incredibly performant and straightforward to use. I am running into one issue which may be an issue with the library, though it's a bit hard to follow the protocol for me so my usage may be off as well.

I'm running into an uncaught error during the `parseComplete` handler in client.js (https://github.com/brianc/node-postgres/blob/v6.0.1/lib/client.js#L131).

I am doing a direct `connect` against the pool and then utilizing pg-query-stream

``` javascript
pool.connect().then(function(client){
  stream = client.query(new QueryStream(query, null));

  stream.on('error', function(streamError){
    stream.close(function(closeError){ 
      // What to do with a close error? At this point stream is already hosed :shrug:
      client.release(streamError);
    }
  });

  stream.on('close', function(){
    client.release();
  }); 
});
```

At some point during my app's life cycle, I get an uncaught error

```
TypeError: Cannot read property 'name' of null
    at null.<anonymous> (/var/app/current/node_modules/pg/lib/client.js:139:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:121:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
```

So obviously `activeQuery` is becoming null, and I am trying to narrow down why I would receive a `parseComplete` event when the active query is null.

According to my logs, the stream is _not_ emitting an error, and seems to be closing normally. Therefore it seems like the connection client is getting a `readyForQuery` or `end` event, and then right after that getting the `parseComplete` event. Any idea why this would be happening, or see any issues with my usage? Thanks for any help you can give! I'll keep looking into it as well.

### PR DESCRIPTION
**Pull request by mrhwick**

### CODE REVIEW

**Comment by brianc** [comment]
Hey nice! Is there any way to write a test for this?

**Comment by brianc** [comment]
Thanks for the test! I'll wait on @charmander for a second pair of :eyes: and then merge if it looks good to him.

**Comment by charmander** [comment]
Silently ignoring invalid data without knowing why it’s there seems dangerous.

**Comment by mrhwick** [comment]
If the query isn't there, then the name isn't there either. This doesn't
change the semantics of the conditional or the functioning of this event
listener. It only safeguards against a null reference exception.

**Comment by charmander** [comment]
> This doesn't change the semantics of the conditional

It does. The original is “mark this query as parsed if it has a name”, because preparing a query without a name is normal (it’s how all parameterized queries work). The new meaning is “make sure the active query exists because it might not because ???”

**Comment by mrhwick** [comment]
If it doesn't exist, it can't have a name.

**Comment by mrhwick** [comment]
https://github.com/brianc/node-postgres/blob/ecab41c3f3d07230b24253e804971367cd04fb53/lib/client.js#L128-L135

**Comment by charmander** [comment]
> Since this can happen **under some set of circumstances**

Which ones? This is really important.

**Comment by mrhwick** [comment]
[Here is a set of circumstances where this error occurs](https://github.com/brianc/node-postgres/issues/1674). 

Maybe this PR could be changed to throw a more descriptive error rather than the TypeError that is currently thrown? If you would rather continue throwing a TypeError up to your users, I'll close this PR.

**Comment by mrhwick** [comment]
Understood. No appetite for throwing a more meaningful error to your users. Closing this PR instead of changing it to do that.

**Pull request closed without merging**
