### PR TITLE
fix devcontainer

### PR DESCRIPTION
**Pull request by nigrosimone**
- Fix: Debian stretch repo has been moved to archive.debian.org
- Fix: Scam autentication required
- Fix: Add missing library for pg-native
- Fix: Internal network connection

Also fix https://github.com/brianc/node-postgres/issues/3049

### CODE REVIEW

**Comment by brianc** [comment]
Thanks! Will be a bit slow to follow up as I'm in the mountains for a few more days - will be home in a few in case I seem awol.

**Comment by brianc** [comment]
I'm a bit confused as to why the tests are failing? Nothing you changed should have impacted the tests at all afaict?  any ideas?...

**Comment by nigrosimone** [comment]
> I'm a bit confused as to why the tests are failing? Nothing you changed should have impacted the tests at all afaict? any ideas?...

Into the github action the database host is "localhost" https://github.com/brianc/node-postgres/blob/master/.github/workflows/ci.yml#L52, Instead into devcontainer is "db" https://github.com/nigrosimone/node-postgres/blob/patch-1/.devcontainer/docker-compose.yml#L44.

The test run successfully into devcontainer, but fail into github action. Simply need to use the same host name

**Comment by brianc** [comment]
k - should probably revert the changes to the native test or make it consistent everywhere - can't merge this w/o tests passing!

**Comment by nigrosimone** [comment]
@brianc I have reverted the failing test and made some other changes for latest vscode

**Comment by brianc** [comment]
@nigrosimone thanks for your help! Will run tests & then merge this. ❤️

**Pull request merged**
