### PR TITLE
Remove confusing conditions

### PR DESCRIPTION
**Pull request by charmander**
One of these is unreachable, and the other suggests that there’s special behaviour where there isn’t.

### CODE REVIEW

**Comment by brianc** [comment]
@charmander think you could rebase your branch with master so we pick up the fixes you did for travis? After that I'll happily merge, or _you_ can if you want to be a contributor!

**Comment by charmander** [comment]
@brianc Done!

**Comment by brianc** [comment]
Boom! Nice!

**Comment by brianc** [comment]
Made you contributor! Feel free to merge whatever you think is best!

**Pull request merged**
