### PR TITLE
Add failing connection pool test for server errors

### PR DESCRIPTION
**Pull request by sehrope**
As this is a failing test it really shouldn't be merged in until a fix is found for it. I'm adding it as a PR so a fix can be built atop it.

### CODE REVIEW

**Comment by brianc** [comment]
Nice! What's the expected behavior here?  The `pg` object will emit an error event when a client in the pool disconnects - should we handle that error & test for it?

**Comment by sehrope** [comment]
> Nice! What's the expected behavior here?

Well not crashing the node process would be nice :)

As far as handling the error goes, it's a toss up between silently swallowing/logging it or saving it to dish out the next time that particular connection is checked out. I don't really see much value in the latter as if the server has been bounced most people would want a fresh connection (*i.e. transparent recovery*). If the server is still down (*i.e. the entire pool got flushed*), a new connection will be attempted and you'll get the error for that anyway. Probably would be more complicated too v.s. just swallowing it.

> The pg object will emit an error event when a client in the pool disconnects - should we handle that error & test for it?

Yes following up from info in #821 I'm going to test some options of adding a default handler to the `pg` object to catch these. Note that it shouldn't handle all errors, just errors for non-checked out pooled connections. The alternative is to document that everybody using pooled connections manually add their own top level error handler but that doesn't sound like a good idea.

**Comment by brianc** [comment]
@sehrope I know it's taken me a while to get to it but I _think_ this should fix the error!  :smile: 

https://github.com/brianc/node-postgres/pull/843

**Comment by sehrope** [comment]
Haven't had a chance to test this out yet but this looks like exactly what's need. Great idea to add/remove the error handler when the connection is idle in the pool. 

With how the rest of the error handling works, this would leave the bad connection in the pool right? So the next checkout of that connection would fail? If so, I wonder if there's a way to dispose the connection entirely. I don't see any value in having failed connections linger in the pool. Otherwise if you have a pool of size N, you'd need N checkouts to "flush" them out.

Still better than the entire node process crashing though :smile:...

**Comment by sehrope** [comment]
Peeking through the code a bit, I think this fixes errors on first connect but not if the server is bounced after things have already been running. The same approach of should work for that too.

We'd need to add/remove the error handler when the connection is [checked out](https://github.com/brianc/node-postgres/blob/35e5567f86774f808c2a8518dd312b8aa3586693/lib/pool.js#L82) and [checked back in](https://github.com/brianc/node-postgres/blob/35e5567f86774f808c2a8518dd312b8aa3586693/lib/pool.js#L86).

**Comment by brianc** [comment]
Closing this because it's 18 months old.  If it's still relevant I apologize: doing some house-cleaning before I start really going to town on fixing up some stuff & prepping for 7.0.

**Pull request closed without merging**
