### PR TITLE
minor pedantry, use destructuring 🙏

### PR DESCRIPTION
**Pull request by Lewiscowles1986**

### CODE REVIEW

**Comment by charmander** [comment]
this is a style change of little benefit that introduces style mistakes, sorry

**Comment by Lewiscowles1986** [comment]
If you did have more to share regarding:
> style mistakes
I'd be keen to understand what you believe is mistaken.

**Comment by charmander** [comment]
Semicolons don’t match the surrounding code.

**Comment by Lewiscowles1986** [comment]
Oh man... thanks.

**Pull request closed without merging**
