### PR TITLE
Remove console.error on pg-native module not found

### PR DESCRIPTION
**Pull request by caseywebdev**
Re https://github.com/brianc/node-postgres/issues/2358#issuecomment-706405845

### CODE REVIEW

**Comment by mjsalinger** [comment]
@brianc Can this be merged?

**Comment by brianc** [comment]
Im out of town until Monday. I will look then.

**Comment by mjsalinger** [comment]
Any update @brianc ?

**Review by charmander — APPROVED** [review]
This looks like the best fully-backwards-compatible solution.

**Comment by brianc** [comment]
sorry for the delay!

**Pull request merged**
