### PR TITLE
escapeLiteral handles more types of input

### PR DESCRIPTION
**Pull request by andythiv**
I added functionality to escape more kinds of values instead of only just strings similar to the way other SQL libraries do it:
https://www.npmjs.com/package/mysql#escaping-query-values

I left the existing code for handling strings in place and now also handle null, undefined, numbers, booleans, and arrays. The only strange thing might be that if the value being escaped is not one of those types, I just pass it back.

### CODE REVIEW

**Comment by andythiv** [comment]
First I had a jshint failure, but I added an ignore and an explanation for it, which I think you should find acceptable.

However, now I have a problem with a unit test that relies on checking a string output based on a Date object, so the timezone the test runs in makes a difference. I thought I already accounted for this, but I'm looking into it now.

**Comment by andythiv** [comment]
Fixed it

**Comment by andythiv** [comment]
Fixed merge conflict

**Comment by abenhamdine** [comment]
Great !
I am very interested by this
@brianc would it be possible for you to review and merge this one ?

**Comment by brianc** [comment]
First of all, let me say I'm sorry for missing this when it first came in!  :grimacing: 

@rpedela initially ported the libpq version of escape literal to JavaScript, which is what the existing code does.  The mirroring of the libpq version is intentional to provide the 'minimum' version of functionality available to those who don't have access to a compiler & libpq native bindings.  

I'm not sure extending this with extra escaping really belongs inside node-postgres itself.  Is there a reason you couldn't spin this out into a separate module...something like `pg-escape` that one could opt-in to separately with an additional dependency?  This escaping definitely seems helpful, but unless it exists in libpq itself the additions are arbitrary & I could see this growing in complexity & usefulness...which is a perfect place for a different module!

Thoughts?

**Comment by rpedela** [comment]
I made a library specifically for this. It is a Javascript implementation of PG's built-in function [format()](http://www.postgresql.org/docs/9.4/static/functions-string.html#FUNCTIONS-STRING-FORMAT). It also handles all Node.js types including JSON and buffers. The library is pretty mature, but I am happy to resolve issues or take PRs.

https://github.com/datalanche/node-pg-format

**Comment by brianc** [comment]
@rpedela to the rescue! :dancer:

**Comment by rpedela** [comment]
LOL! :)

**Comment by abenhamdine** [comment]
@rpedela thanks for this module !

**Comment by brianc** [comment]
I'm going to close this in favor of using @rpedela's node-pg-format module. :smile:

**Comment by rpedela** [comment]
Just an idea. The status quo is good too.

What if the source was kept as a module but it was included in the main ```pg``` as a replacement for the escape functions? I think it would help people write better raw SQL, and it isn't intrusive. For example, this is a trivial example of how I usually use the module.

```javascript
var pg = require('pg');
pg.format = require('pg-format');

var sql = pg.format('SELECT * FROM t where c = %L', 34);
var client = new pg.Client('postgres://username:password@localhost/database');

client.connect(function (err) {

    if (err) {
        return console.error(err);
    }

    client.query(sql, function (err, result) {

        client.end();

        if (err) {
            return console.error(err);
        }

        console.log(result);
    });
});
```

**Pull request closed without merging**
