### PR TITLE
Use Buffer concatenation for binary data instead of binary strings. F…

### PR DESCRIPTION
**Pull request by ignitenet-martynas**
…ixes Node.js v6.0.0 breakage.

### CODE REVIEW

**Comment by jadbox** [comment]
LGTM

**Comment by vitaly-t** [comment]
It will be logical to release this as version 4.6.0 ;)

**Comment by djMax** [comment]
Confirm this fixes it for me too, would love this to get released soon so I can update our various consumers to node6.

**Comment by vitaly-t** [comment]
[.travis.yml](https://github.com/brianc/node-postgres/blob/master/.travis.yml) needs to be extended at the same time, to include both `5.x` and `6.x` Node.js versions.

**Comment by brianc** [comment]
Hey thanks for putting this together @ignitenet-martynas & everyone else for digging in & looking at this.  I'll push a new patch version now & add `node@v6.x` to the travis.yml in a separate PR.

❤️

**Pull request merged**
