### PR TITLE
chore (ci): add node v20 to build matrix

### PR DESCRIPTION
**Pull request by alxndrsn**
Per https://nodejs.org/en/about/previous-releases, node v20 is "active".

`pg-native` tests are skipped on Node 20 __TODO because pg-native doesn't support node 20?__

### CODE REVIEW

**Comment by brianc** [comment]
Appreciate your thought here! This got added on another PR actually...but thank you! sorry for the delay ❤️

**Comment by brianc** [comment]
Oopps! My bad - it actually did _not_ get added. I can add it if you want. Otherwise you'll need to rebase here and pick up the fixes that were done on master to make CI pass. 😅

**Comment by alxndrsn** [comment]
@brianc :+1: should be fixed

**Comment by alxndrsn** [comment]
Hmm failing no node 20:

```
***Testing native bindings***

changed 2 packages, and audited 1087 packages in 5s

74 packages are looking for funding
  run `npm fund` for details

28 vulnerabilities (11 low, 6 moderate, 5 high, 6 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
evented-api-tests.jsMessage: Cannot find module 'pg-native'
Require stack:
- /home/runner/work/node-postgres/node-postgres/packages/pg/lib/native/client.js
- /home/runner/work/node-postgres/node-postgres/packages/pg/lib/native/index.js
- /home/runner/work/node-postgres/node-postgres/packages/pg/test/native/evented-api-tests.js
Error: Cannot find module 'pg-native'
Require stack:
- /home/runner/work/node-postgres/node-postgres/packages/pg/lib/native/client.js
- /home/runner/work/node-postgres/node-postgres/packages/pg/lib/native/index.js
xargs: node: exited with status 255; aborting
- /home/runner/work/node-postgres/node-postgres/packages/pg/test/native/evented-api-tests.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/runner/work/node-postgres/node-postgres/packages/pg/lib/native/client.js:7:12)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)

make: *** [Makefile:43: test-native] Error 124
```

**Comment by alxndrsn** [comment]
Adding `NODE_DEBUG=module` breaks the build on other node versions too :thinking:

**Comment by alxndrsn** [comment]
On failing builds, `@npm i --no-save pg-native` does not install anything:

### working

```
...
added 10 packages, changed 5 packages, and audited 1097 packages in 8s
```

### broken

```
...
changed 2 packages, and audited 1087 packages in 6s
```

**Comment by alxndrsn** [comment]
pg-native build fails on node 20; perhaps that is related.  Ref:

* PR: https://github.com/brianc/node-pg-native/pull/121
* build: https://github.com/alxndrsn/node-pg-native/actions/runs/8294076732

Maybe related to https://github.com/brianc/node-postgres/issues/2955?

**Comment by brianc** [comment]
Doh! Looks like node-libpq isn't compiling on node 20. Makes sense...I'll see about updating that lib as soon as I'm out of my current job & get more time to really pour some fire on this project!! For now, we'll just skip the native version in CI - really appreciate you! ❤️

**Pull request merged**
