### PR TITLE
7.0

### PR DESCRIPTION
**Pull request by brianc**
Notable breaking changes:

- drop support for node < 4.x
- `client.query` no longer returns an event-emitter.  If a callback is supplied, it returns undefined. If no callback is supplied it returns a `Promise.`  This was deprecated in `pg@6.x`
- `pg.connect` and `pg.end` global singleton pool was removed.  This was deprecated in `pg@6.x`
- `pg.cancel` which used the global singleton pool was removed. This was deprecated in pg@6.x`
- standardized error message fields between pure JavaScript driver and libpq driver.  Pure JavaScript error fields are used throughout.  This will only impact you if you were using `pg.native` and checking error feilds such as `error.context` or `error.where` [change](https://github.com/brianc/node-postgres/commit/056f42cd6a49c5e639f3247ce133b15c302b7ccd)
- Result from multi-statement plain text query now returned as multiple arrays instead of mangled into a single array. [context](https://github.com/brianc/node-postgres/issues/508)

Enhancements:
- better promisification of all APIs. connect, end, and query
- better support for network partitions & ensuring errors from connections are bubbled up
- overhaul of pg-pool internals & supporting `connectionTimeoutMillis` for a connection timeout feature in the pool

### CODE REVIEW

**Comment by abenhamdine** [comment]
Amazing !

**Comment by ashking** [comment]
Excellent work! this is exactly the kind of list I was looking for!

**Comment by brianc** [comment]
@ashking I also maintain [this](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md) on every release above patch. :smile:

**Comment by abenhamdine** [comment]
> Result from multi-statement text queries such as `SELECT 1; SELECT 2;` are now returned as an array of results instead of a single result with 1 array containing rows from both queries.

This one is the mega bonus / christmas gift 😄

**Pull request merged**
