### PR TITLE
Update ESLint

### PR DESCRIPTION
**Pull request by kibertoad**
Also make minor formatting change to make new rules pass

### CODE REVIEW

**Comment by charmander** [comment]
Not introduced by this pull request, but I’m not sure why eslint-plugin-import is a dependency.

**Comment by kibertoad** [comment]
@charmander Should I remove it?

**Comment by brianc** [comment]
@kibertoad - thanks for this! If it's not needed it'd be nice to remove it, yeah.  If you find out it's needed lmk.  Either way I'll merge this whenever you're ready.  Thanks for doing the somewhat thankless work of upgrading deps.

**Comment by kibertoad** [comment]
Sorry, will create a separate pr for eslint-plugin-import removal.

**Pull request merged**
