### PR TITLE
Update utils.js

### PR DESCRIPTION
**Pull request by sudarshanvn**
Fixed following error

    ReferenceError: TextEncoder is not defined

### CODE REVIEW

**Comment by sudarshanvn** [comment]
Fixed the following error in Node.Js 16 version
    ReferenceError: TextEncoder is not defined

**Comment by brianc** [comment]
oh nice fix thank you!!

**Comment by sudarshanvn** [comment]
When I can expect these changes to go live ??

**Comment by charmander** [comment]
> in Node.Js 16 version

Are you sure? [The Node documentation](https://nodejs.org/api/globals.html#textencoder) shows that `TextEncoder` and `TextDecoder` have been globals since version 11.0.0. On top of that, pg’s CI, which covers this, already passed on all supported versions.

**Comment by sudarshanvn** [comment]
@charmander  @brianc 

I`m seeing this issue in NodeJs 16 and NodeJs 18 version

image

Debugger attached.
 FAIL  test/client-alert-task-get.spec.js
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

       6 | /* eslint-disable import/no-unresolved */
       7 | const ExceptionWrapper = require('exception-handler');
    >  8 | const ReqParserFramework = require('medifast-framework').RequestParser;
         |                            ^
       9 | const commonMessage = require('./constants/common-messages');
      10 |
      11 | const exceptionHandler = new ExceptionWrapper();

      at Object.<anonymous> (../../../common/layer/medifast-framework/dependencies/nodejs/node_modules/medifast-framework/node_modules/pg/lib/crypto/utils.js:31:21)

**Comment by sudarshanvn** [comment]
to fix this issue, I have added the following code in  packages/pg/lib/crypto/utils.js file

const { TextEncoder, TextDecoder } = require('util');

**Comment by john-laird** [comment]
@sudarshanvn - we actually had the same issue, this comment solved the problem for us: https://stackoverflow.com/a/73454657

**Pull request merged**
