### PR TITLE
Mark the native property as non-enumerable. Closes #945

### LINKED ISSUE #945: Cloning the library throws error when pg-native is not installed
Related to https://github.com/sequelize/sequelize/pull/5438 and https://github.com/sequelize/sequelize/issues/5476.

``` js
var pg = require('pg')
_.clone(pg);
```

Throws `Error: Cannot find module 'pg-native'`

Wanting to clone the library directly doesn't make much sense, but in the issues linked above, it happens because a sequelize model, which has a reference to pg is being deeply cloned. 

This should be fixable by switching to `defineProperty` and marking the `native` property as non-enumerable. 

I can write up a PR later today if you'd like - I just need a hint as to where to put the test

### PR DESCRIPTION
**Pull request by janmeier**

### CODE REVIEW

**Comment by janmeier** [comment]
@brianc Tests pass now :)

**Comment by brianc** [comment]
Very nice!  I think this probably could break backwards compatibility in some weird edge cases - what do you think?  I think it should be a major version bump.

**Comment by janmeier** [comment]
Not sure I can think of any cases right now - Would users every purposefully enumerate the object? The only cases I can think of are when the pg object is cloned as a child of something else

**Comment by langpavel** [comment]
@janmeier users brobably don't enumerate but babel or webpack can. This was debated in #950

**Comment by brianc** [comment]
Yeah sorry for dropping the ball on this one...

I've been busy w/ life stuff.  I see there is [this pr](https://github.com/brianc/node-postgres/pull/950) as well.  Do you want me to unify the changes between these two PRs & submit a new PR that does both of these in combo?  I think both changes make sense & fix different parts of the issue.

**Comment by janmeier** [comment]
@brianc Yeah that would be nice! :)

**Comment by brianc** [comment]
I believe this is fixed in 5.1

**Pull request closed without merging**
